name: Shared CI

on:
  workflow_call:
    outputs:
      generated-pdfs:
        description: "List of generated PDF resumes"
        value: ${{ jobs.get-generated-pdfs.outputs.generated-pdfs }}
      pdfs-root-path:
        description: "Path to the generated PDFs directory"
        value: ${{ jobs.get-generated-pdfs.outputs.pdfs-root-path }}

permissions: {}

env:
  RESUME_PDFS_ROOT_PATH: resume/pdf

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@5ac504609f6ef35c5ac94bd8199063aa32104721 # 0.31.3
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write

  validate-resumes:
    name: Validate Resumes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        resume-language: [en, fr]
      fail-fast: false
    env:
      RESUME_FILE: resume/resume.${{ matrix.resume-language }}.json
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Validate English resume
        uses: ./.github/actions/validate-resume
        with:
          resume-path: ${{ env.RESUME_FILE }}

  theme-continuous-integration:
    needs: [linter, validate-resumes]
    name: Resume Theme CI
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@338755b95043af1f8aa17409529fd20a9d2ef659 # 0.20.6
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    with:
      working-directory: resume/theme
      build: |
        {"artifact": ["dist"]}
      lint: null

  generate-pdfs:
    name: Generate PDF Resumes
    runs-on: ubuntu-latest
    needs: theme-continuous-integration
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        resume-language: [en, fr]
    env:
      RESUME_FILE: resume/resume.${{ matrix.resume-language }}.json
      OUTPUT_FILE: resume/pdf/resume.${{ matrix.resume-language }}.pdf
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          artifact-ids: ${{ needs.theme-continuous-integration.outputs.build-artifact-id }}
          path: /

      - name: Generate English PDF
        uses: ./.github/actions/generate-resume-pdf
        with:
          resume-path: ${{ env.RESUME_FILE }}
          output-path: ${{ env.OUTPUT_FILE }}

      - name: Upload PDF artifacts
        id: upload-artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: resume-pdf-${{ matrix.resume-language }}
          path: ${{ env.OUTPUT_FILE }}
          if-no-files-found: error

      - uses: hoverkraft-tech/ci-github-common/actions/set-matrix-output@5ac504609f6ef35c5ac94bd8199063aa32104721 # 0.31.3
        with:
          value: |
            {
              "language": ${{ toJSON(matrix.resume-language) }},
              "pdf-path": ${{ toJSON(env.OUTPUT_FILE) }},
              "artifact-url": ${{ toJSON(steps.upload-artifact.outputs.artifact-url) }},
              "artifact-id": ${{ toJSON(steps.upload-artifact.outputs.artifact-id) }}
            }
          artifact-name: generated-pdfs

  get-generated-pdfs:
    name: Get Generated PDFs
    runs-on: ubuntu-latest
    needs: generate-pdfs
    outputs:
      generated-pdfs: ${{ steps.get-generated-pdfs.outputs.result }}
      pdfs-root-path: ${{ env.RESUME_PDFS_ROOT_PATH }}
    steps:
      - id: get-generated-pdfs
        uses: hoverkraft-tech/ci-github-common/actions/get-matrix-outputs@5ac504609f6ef35c5ac94bd8199063aa32104721 # 0.31.3
        with:
          artifact-name: "generated-pdfs"
